In [ ]:
import pandas as pd

In [3]:
movies=pd.read_csv('top10K-TMDB-movies.csv')

In [7]:
movies.head(5)

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [8]:
movies.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [17]:
movies.isnull()

         id  title  overview  genre
0     False  False     False  False
1     False  False     False  False
2     False  False     False  False
3     False  False     False  False
4     False  False     False  False
...     ...    ...       ...    ...
9995  False  False     False  False
9996  False  False     False  False
9997  False  False     False  False
9998  False  False     False  False
9999  False  False     False  False

[10000 rows x 4 columns]

Feature Selection

In [13]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [14]:
movies=movies[['id','title','overview','genre']]

In [15]:
movies

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime"

In [ ]:
movies['tags'] = movies['overview'] + movies['genre']

C:\Users\User\AppData\Local\Temp\ipykernel_20720\2958959546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genre']

In [24]:
movies

,id,title,overview,genre,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [26]:
new_data = movies.drop(columns=['overview' , 'genre'])

In [27]:
new_data

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

Convert the English Strings or movie features into vector(array) features

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
cv=CountVectorizer(max_features=1000,stop_words='english')

In [32]:
cv

CountVectorizer(max_features=1000, stop_words='english')

In [37]:
vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

In [42]:
similarity=  cosine_similarity(vector)

In [43]:
similarity

array([[1.        , 0.10114435, 0.20851441, ..., 0.11616046, 0.16718346,
        0.09325048],
       [0.10114435, 1.        , 0.14552138, ..., 0.        , 0.06482037,
        0.        ],
       [0.20851441, 0.14552138, 1.        , ..., 0.03713907, 0.1069045 ,
        0.13416408],
       ...,
       [0.11616046, 0.        , 0.03713907, ..., 1.        , 0.04962917,
        0.04152274],
       [0.16718346, 0.06482037, 0.1069045 , ..., 0.04962917, 1.        ,
        0.05976143],
       [0.09325048, 0.        , 0.13416408, ..., 0.04152274, 0.05976143,
        1.        ]], shape=(10000, 10000))

In [45]:
new_data[new_data['title']=="The Godfather"]

    id          title                                               tags
2  238  The Godfather  Spanning the years 1945 to 1955, a chronicle o...

In [50]:
distance=sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
House of Gucci
Batman: The Killing Joke
Bomb City

In [53]:
def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance=sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
       print(new_data.iloc[i[0]].title)

In [56]:
recommand("Iron Man")

Iron Man
Guardians of the Galaxy Vol. 2
Star Wars: Episode III - Revenge of the Sith
G.O.R.A.
Mad Max Beyond Thunderdome

In [57]:
import pickle

In [58]:
pickle.dump(new_data,open('movies_list.pkl','wb'))

In [61]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [60]:
pickle.load(open('movies_list.pkl','rb'))

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

In [62]:
pickle.load(open('similarity.pkl','rb'))

array([[1.        , 0.10114435, 0.20851441, ..., 0.11616046, 0.16718346,
        0.09325048],
       [0.10114435, 1.        , 0.14552138, ..., 0.        , 0.06482037,
        0.        ],
       [0.20851441, 0.14552138, 1.        , ..., 0.03713907, 0.1069045 ,
        0.13416408],
       ...,
       [0.11616046, 0.        , 0.03713907, ..., 1.        , 0.04962917,
        0.04152274],
       [0.16718346, 0.06482037, 0.1069045 , ..., 0.04962917, 1.        ,
        0.05976143],
       [0.09325048, 0.        , 0.13416408, ..., 0.04152274, 0.05976143,
        1.        ]], shape=(10000, 10000))